<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13367" started-at="2020-03-10T13:55:59Z" finished-at="2020-03-10T13:56:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13367" started-at="2020-03-10T13:55:59Z" finished-at="2020-03-10T13:56:12Z">
      <class name="test.testcases">
        <test-method status="PASS" signature="startup()[pri:0, instance:test.testcases@523884b2]" name="startup" is-config="true" duration-ms="10629" started-at="2020-03-10T13:55:59Z" finished-at="2020-03-10T13:56:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method status="FAIL" signature="Login()[pri:0, instance:test.testcases@523884b2]" name="Login" duration-ms="70" started-at="2020-03-10T13:56:10Z" finished-at="2020-03-10T13:56:10Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at page.mainpage.Login_click(mainpage.java:18)
at test.testcases.Login(testcases.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="contact()[pri:0, instance:test.testcases@523884b2]" name="contact" duration-ms="3" started-at="2020-03-10T13:56:10Z" finished-at="2020-03-10T13:56:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contact -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:test.testcases@523884b2]" name="afterClass" is-config="true" duration-ms="2528" started-at="2020-03-10T13:56:10Z" finished-at="2020-03-10T13:56:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- test.testcases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
